version: "3.9"

services:
  api:
    build: .
    container_name: ia_blog_api
    ports:
      - "8000:10000"   # local:container
    env_file:
      - .env
    volumes:
      - ./app/static/images:/app/app/static/images  # mantener im√°genes fuera del contenedor
    restart: unless-stopped
